### PR TITLE
Add FY-4A AGRI support

### PR DESCRIPTION
**Pull request by zxdawn**
Add the FY-4A AGRI relative spectral responses.
The link of data: http://fy4.nsmc.org.cn/portal/cn/fycv/srf.html

### CODE REVIEW

**Comment by mraspaud** [comment]
[FY4A_AGRI_SRF_20180306.pdf](https://github.com/pytroll/pyspectral/files/3350016/FY4A_AGRI_SRF_20180306.pdf)

**Comment by zxdawn** [comment]
[FY4A_SRF.tar.gz](https://github.com/pytroll/pyspectral/files/3350020/FY4A_SRF.tar.gz)

**Comment by adybbroe** [comment]
@zxdawn I finally took a look at your work. Sorry for the delay! It looks in general fine, only one small thing I found: The original RSR data are in nanometers for the three first bands, so there the default scale of 0.001 works fine (you get micrometers as expected by pyspectral). But for the rest of the bands the data appears to be in micrometers. So, there the scale should be 1.0.
I fixed it locally. Should I push? Not sure I am allowed to push to your fork though?

Also, I see that in your data, there is two files for the 3.75 band, though the RSR are identical. I suppose that is why the NWPSAF only has 13 bands and not 14 as in your case. I notice that band 7 and 8 on AGRI are different in terms of resolution, but looks like it is actually the same band in terms of sensor?

**Comment by adybbroe** [comment]
@zxdawn Maybe you can allow me to push to your fork?

**Comment by zxdawn** [comment]
> @zxdawn I finally took a look at your work. Sorry for the delay! It looks in general fine, only one small thing I found: The original RSR data are in nanometers for the three first bands, so there the default scale of 0.001 works fine (you get micrometers as expected by pyspectral). But for the rest of the bands the data appears to be in micrometers. So, there the scale should be 1.0.
> I fixed it locally. Should I push? Not sure I am allowed to push to your fork though?
> 
> Also, I see that in your data, there is two files for the 3.75 band, though the RSR are identical. I suppose that is why the NWPSAF only has 13 bands and not 14 as in your case. I notice that band 7 and 8 on AGRI are different in terms of resolution, but looks like it is actually the same band in terms of sensor?

Yes, band 7 and band 8 are same for 3.72 um, except the resolution.
Enjoy pushing :)

**Comment by adybbroe** [comment]
I think we can merge, disregarding the failed appveyor builds for the time being - these should be fixed in another PR - it doesn't seem to have with this PR to do.

**Pull request merged**
