### PR TITLE
Separate masking and Sun zenith angle correction

### LINKED ISSUE #112: Do not cut NIR reflectance with a single threshold
#### Code Sample, a minimal, complete, and verifiable piece of code

```python
import glob
from satpy import Scene

fnames = glob.glob("/path/to/msg/data/H*__")
glbl = glbl.load(["day_microphysics"])
lcl = glbl.resample("euro4")
lcl.show("day_microphysics")
```

#### Problem description

The above code using Satpy uses Pyspectral to determine the NIR reflectance and uses it as one channel in the RGB. Current version of Pyspectral masks the data with a single strict limit of Sun zenith angle (85.0 degrees by default). The same limit is used to limit the range of SZA correction. These two should be separated. When this composite is used together with a night-side composite, there's a big gap between the composites.

#### Expected Output
Adjustable limit for masking invalid data by SZA.

#### Actual Result, Traceback if applicable
day_microphysical_20161128_110000

#### Proposed solution
Separate the SZA limit (`sunz_threshold` kwarg) and the masking limit of invalid data. So I would add another keyword argument to `pyspectral.near_infrared_reflectance.Calculator.__init__`. Maybe `masking_limit`. By default these both can have the same limit (`TERMINATOR_LIMIT`), but for Day/Night composites the masking limit should be adaptable.

#### Versions of Python, package at hand and relevant dependencies
Current master branch of Pyspectral.

### PR DESCRIPTION
**Pull request by pnuu**
This PR separates the Sun zenith-angle correction and masking of data beyond given SZA limit.

 - [x] Closes #112  
 - [x] Tests added 
 - [x] Tests passed: Passes ``pytest pyspectral`` 
 - [x] Passes ``flake8 pyspectral`` 
 - [x] Fully documented

### CODE REVIEW

**Comment by pnuu** [comment]
And here's an example using a matching Satpy PR (yet-to-be-PR'd) branch:

day_microphysical_with_night_microphysical_20200320_180000

This provides much better looking results than the ones in #112

**Comment by pnuu** [comment]
Travis tests fail here: https://github.com/pytroll/pyspectral/blob/master/pyspectral/tests/test_reflectance.py#L181
The same test passes locally, don't know what's going on..

**Comment by pnuu** [comment]
I had `numpy` 0.17.5 so tried upgrading to `0.19.1` which Travis used: still passes locally.

**Comment by mraspaud** [comment]
@pnuu the error seems to come from conda failing on python 2.7, so I don't there is much you can do about it.

**Comment by pnuu** [comment]
Hmm. I'm quite sure the other three jobs had a failure in the test I linked above, but now they've passed. Weird. Didn't notice the erroring test is from Python 2.7, makes sense it errors as it's not supported by Travis anymore.

**Comment by mraspaud** [comment]
Just opened #114 to remove 2.7 testing.

**Comment by adybbroe** [comment]
Sorry about your troubles @pnuu . @mraspaud is right, python 2.7 testing on Travis has failed a long time now. #116 should solve this. We leave Python 2.7 alltogether

**Review by adybbroe — APPROVED** [review]
LGTM

**Comment by adybbroe** [comment]
Thanks for the nice work @pnuu !

**Pull request merged**
