### PR TITLE
Remove all use of 'six'

### PR DESCRIPTION
**Pull request by pnuu**
This PR removes the use of 'six' Python 2.7 compatibility library

### CODE REVIEW

**Comment by djhoese** [comment]
Are these failures due to a new version of numpy and/or dask? They don't seem related to your changes.

**Comment by pnuu** [comment]
@adybbroe found out that downgrading to `dask=2021.05.0` all the tests pass. Verified this locally.

**Comment by pnuu** [comment]
With version 2021.05.0:
```
/home/lahtinep/mambaforge/envs/pytroll/lib/python3.9/site-packages/dask/array/core.py:1514: FutureWarning: The `numpy.searchsorted` function is not implemented by Dask array. You may want to use the da.map_blocks function or something similar to silence this warning. Your code may stop working in a future release.
```

**Review by adybbroe — APPROVED** [review]
LGTM.
Thanks for this!

**Comment by pnuu** [comment]
The unstable tests are fixed in #134.

**Pull request merged**
