### PR TITLE
Fix NIR computations to be more lenient towards dask arrays

### PR DESCRIPTION
**Pull request by mraspaud**
This PR mostly fixes unwanted computations of dask arrays

 - [ ] Tests added 
 - [x] Tests passed: Passes ``pytest pyspectral`` 
 - [x] Passes ``flake8 pyspectral``

### CODE REVIEW

**Comment by adybbroe** [comment]
Is it okay to merge @mraspaud ?
Did you test it on more than one use case? Is there more testing needed?

**Comment by mraspaud** [comment]
It's been tested against https://github.com/pytroll/satpy/pull/1011 and work well. Just for one use case, so testing other cases would be nice. (I tested only one composite with ears-viirs data, so maybe we should test geo).
One thing to note it that this PR will break satpy master and previous releases, so the releasing of this should be timed with the next release of satpy.

**Comment by adybbroe** [comment]
Ok @mraspaud Could you test a SEVIR case? 
Otherwise the Satpy master is already updated, so I guess we need to merge this now in order to have Satpy and Pyspectral master branches to be in sync?

**Comment by mraspaud** [comment]
yes, that's right, but in the current state, satpy master souldn't have a problem with this master.
I'll test Seviri right now

**Comment by mraspaud** [comment]
Looks fine on SEVIRI!
snow

**Comment by adybbroe** [comment]
Okay, great @mraspaud . Merging...

**Pull request merged**
