### PR TITLE
add more realistic METimage RSRs

### PR DESCRIPTION
**Pull request by rolle-at-work**
Updated to more realistic, though not measured spectral response functions for METimage

 - [ ] Closes #xxxx 
 - [ ] Tests added 
 - [x] Tests passed: Passes ``pytest pyspectral`` 
 - [x] Passes ``flake8 pyspectral`` 
 - [ ] Fully documented

### CODE REVIEW

**Comment by rolle-at-work** [comment]
The new file looks good and i tested reading with hdfview and a pyspectral plotting routine.

**Comment by rolle-at-work** [comment]
@adybbroe But is this layer also gone for AVHRR and other one-detector instruments? I think this layer was usefull to allow for a general reader of bof both single and multi detector instruments.

**Comment by adybbroe** [comment]
Yes @rolle-at-work they are gone for all single detector sensors. They should be at least. I just checked a couple. And the reader can handle both, no problem

**Comment by adybbroe** [comment]
Oh well, now I look back in the history here: 
https://github.com/pytroll/pyspectral/pull/68
Seems like we were preparing for more detectors. So, if we know there will be, and I gues we do know that @rolle-at-work? Then we should keep it as is I think. Sorry

**Comment by rolle-at-work** [comment]
Yes @adybbroe METimage will have 24 detectors per channel

**Comment by adybbroe** [comment]
@rolle-at-work I have uploaded an updated RSR data archive with your new Metimage data included, please check it out and adapt your PR accordingly. You will need to change version and url of the RSR data in `utils.py` Version should now be `RSR_DATA_VERSION = "v1.0.15"` and the url is now https://zenodo.org/record/3824535/files/pyspectral_rsr_data.tgz

**Pull request merged**
